version: '3'

services:
  multiversx-etl-run:
    ulimits:
      nproc: 65535
    image: multiversx-etl:latest
    container_name: multiversx-etl-run
    volumes:
      - ${WORKSPACE}:/workspace
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/secrets/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/credentials.json
      - GOOGLE_CLOUD_PROJECT=${GCP_PROJECT_ID}
      - WORKSPACE=${WORKSPACE}
    entrypoint:
      [
        "python3.10",
        "-m",
        "multiversxetl",
        "app",
        "--workspace",
        "${WORKSPACE}"
      ]
