SECONDS_IN_MINUTE = 60
SECONDS_IN_FIVE_MINUTES = 5 * SECONDS_IN_MINUTE
SECONDS_IN_DAY = 24 * 60 * SECONDS_IN_MINUTE
SECONDS_IN_THIRTY_DAYS = 30 * SECONDS_IN_DAY
SECONDS_IN_ONE_YEAR = 365 * SECONDS_IN_DAY
MIN_TIME_DELTA_FROM_NOW_FOR_ETL = 30 * SECONDS_IN_MINUTE
